### ISSUE TITLE
multiple-value gopass.????() in single-value context

### ISSUE THREAD

**Issue by asuna** [AustinDizzy/securitycenter-cli#1]
Hello,
I met these errors after run the command: `go get github.com/austindizzy/securitycenter-cli`
Cloud you help me to solve this?
Thanks.

````bash
root@hostname:~# go get -v github.com/austindizzy/securitycenter-cli
github.com/bitly/go-simplejson
github.com/urfave/cli
github.com/austindizzy/securitycenter-cli/api
github.com/austindizzy/securitycenter-cli/utils
github.com/boltdb/bolt
github.com/mattn/go-colorable
github.com/mattn/go-isatty
github.com/fatih/color
golang.org/x/crypto/ssh/terminal
github.com/howeyc/gopass
github.com/austindizzy/securitycenter-cli/auth
# github.com/austindizzy/securitycenter-cli/auth
/usr/local/go/workspace/src/github.com/austindizzy/securitycenter-cli/auth/auth.go:127: multiple-value gopass.GetPasswdMasked() in single-value context
/usr/local/go/workspace/src/github.com/austindizzy/securitycenter-cli/auth/auth.go:129: multiple-value gopass.GetPasswd() in single-value context
github.com/briandowns/spinner
````

Screenshot:
![image](https://cloud.githubusercontent.com/assets/1998862/22183474/389f7940-e0fa-11e6-8329-45c72b5e50b3.png)

**Comment by AustinDizzy** [comment]
Sorry I've let this go on without update, personal events and other time consuming things got in the way of pushing my updates for this project. The gopass library was updated and switched to a multivalue return style to include any errors, so I'll be pushing my change soon which fixes this and keeps track of many other new possible instances of errs across the project.
